### ISSUE TITLE
Not working on Windows 10 (64bits)

### ISSUE THREAD

**Issue by TheDemystifier** [wciesialka/silence-extractor#5]
Popen doesn't seem to be working on Windows :

```
G:\silence-extractor>python main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\bassi\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "G:\silence-extractor\src\gui.py", line 34, in act
    success = extractor.extract(self.inputPath,self.outputPath,self.threshold,self.mode.get()==2)
  File "G:\silence-extractor\src\extractor.py", line 87, in extract
    duration = get_video_duration(input_path)
  File "G:\silence-extractor\src\extractor.py", line 22, in get_video_duration
    probe = ffmpeg.probe(path)
  File "C:\Users\X\AppData\Local\Programs\Python\Python37\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\X\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\X\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by wciesialka** [comment]
Do you have ffmpeg installed?

**Comment by TheDemystifier** [comment]
I'm sorry, it seems to work fine now. It was just a huge overlook on my part. I didn't set up FFmpeg correctly on my computer. Thanks.
Though as a suggestion, is it possible to mark the silences' timestamps and then cut them from the video directly instead of extracting every single frame from the video ? If the video is FullHD and is more than 10 minutes. The frames folder shoots up to 10 gigs easily. Is there another feasible approach ?

**Comment by wciesialka** [comment]
Hmm, it might be possible. I'll look into it.
